name: Release

on:
  release:
    types: [published]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          FILE=$(ls -xm VSIX/vscode-language-scss-*.vsix)
          TAG="${GITHUB_REF##*/}"
          gh release upload "${TAG}" ${FILE}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
